[project]
name = "asus"
languages = ["C", "CXX", "ASM_MASM"]

[target.asus]
type = "shared"

sources = [
    "src/*.cpp",

    "vendor/minhook/**.c",

    "vendor/CppSDK/SDK/Basic.cpp",
    "vendor/CppSDK/SDK/CoreUObject_functions.cpp",
    "vendor/CppSDK/SDK/Engine_functions.cpp",

    "vendor/CppSDK/SDK/ShooterGame_functions.cpp",
]

include-directories = ["src", "vendor"]

link-libraries = ["d3d11", "shcore", "user32"]
compile-features = ["cxx_std_23"]
msvc.compile-options = [
    "/D_UNICODE",
    "/DUNICODE",
    "/O2",
    "/Ot",
    "/Oi",
    "/Gy",
    "/GL",

    "/fp:fast",
    "/Zc:inline",
    "/MT",
]

msvc.link-options = ["/SUBSYSTEM:WINDOWS", "/LTCG", "/OPT:REF", "/OPT:ICF"]
